import 'package:flutter/material.dart';

const KMainColor = Color(0xffFFBD29);
const KSecColor = Color(0xffffe6ac);
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const kProductsCollection = 'Products';
const kBackgroundUserColor = Color(0xff343442);
const kUnActiveColor = Color(0xff777781);
const kJackets='jackets';
const kTrousers='Trousers';
const kTshirts='T-shirts';
const kShoes='Shoes';
const kOrders='Orders';
const kOrderDetails='OrderDetails';
const kTotalPrice='TotalPrice';
const kAddress='Address';
const kProductQuantity='Quantity';